### ISSUE TITLE
Vue warn with Nuxt Devtools enabled on ModalsContainer

### ISSUE THREAD

**Issue by FlorianWerndl** [vue-final/vue-final-modal#453]
This is not a bug, more like a question. 

When using the `<ModalsContainer>` with Nuxt Devtools enabled you get warning like the one below. 
Is there any change to suppress this warning or should this be adressed somewhere else? 

Thank you for the awesome work!

### Version

vue-final-modal: 4.5.5
vue: 3.5.3
nuxt: 3.13.0

### OS

Mac

### Reproduction Link
https://stackblitz.com/edit/nuxt-starter-dnlhxf?file=app.vue

### What is actually happening?
```js
 WARN  [Vue warn]: Extraneous non-props attributes (data-v-inspector) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <ModalsContainer data-v-inspector="app.vue:8:5" > 
  at <App data-v-inspector="node_modules/nuxt/dist/app/components/nuxt-root.vue:16:5" > 
  at <NuxtRoot>
  ```

**Comment by wokalek** [comment]
Will this be fixed?
